# Datasource
spring:
  application:
    name: demo-mybatisplus
  main:
    allow-bean-definition-overriding: true
  datasource:
    dbone:
      url: jdbc:mysql://127.0.0.1:3306/dbone?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: admin
      password: admin
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
    dbtwo:
      url: jdbc:mysql://127.0.0.1:3306/dbtwo?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: admin
      password: admin
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
