server:
  port: 8101

spring:
  application:
    name: nacos-client
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
          # 命名空间
          #        namespace:

#自定义Ribbon的全局配置
#ribbon:
#  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

#自定义Ribbon的细粒度配置
#content-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
feign:
  client:
    config:
      default:
        # NONE: 不输出日志
        # BASIC: 只输出请求方法的URL和响应的状态码以及执行时间
        # HEADERS: 将BASIC信息和请求头信息输出
        # FULL: 输出完整的请求头信息
        logger-level: BASIC
        connect-timeout: 8000
        read-timeout: 8000

  sentinel:
    enabled: true
#  hystrix:
#    enabled: true
