server:
  port: 6001

spring:
  application:
    name: gateway-server
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        # ============================
        - id: oauth-server
          uri: lb://oauth-server
          order: 8001
          predicates:
          - Path=/api-oauth-server/**
          filters:
          - StripPrefix=1
        - id: oauth-client
          uri: lb://oauth-client
          order: 8001
          predicates:
          - Path=/api-oauth-client/**
          filters:
          - StripPrefix=1

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@127.0.0.1:9000/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
