server:
  port: 6003

spring:
  application:
    name: oauth-client
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 100ms

#security:
#  oauth2:
#    client:
#      client-id: user-client
#      client-secret: user-secret-8888
#      user-authorization-uri: http://localhost:6001/api-oauth-server/oauth/authorize
#      access-token-uri: http://localhost:6001/api-oauth-server/oauth/token
#    resource:
#      id: user-client
#      user-info-uri: user-info
#    authorization:
#      check-token-access: http://localhost:6001/api-oauth-server/oauth/check_token

security:
  oauth2:
    client:
      client-id: user-client
      client-secret: user-secret-8888
      user-authorization-uri: http://localhost:6001/api-oauth-server/oauth/authorize
      access-token-uri: http://localhost:6001/api-oauth-server/oauth/token
    resource:
      jwt:
        key-uri: http://localhost:6001/api-oauth-server/oauth/token_key
        key-value: dev


eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@127.0.0.1:9000/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
